--------------------------------------------------------
--  File created - Cuma-Ocak-22-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_FATURA
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."SEQ_FATURA"  MINVALUE 100001 MAXVALUE 999999 INCREMENT BY 1 START WITH 100001 NOCACHE  NOORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_KULL
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."SEQ_KULL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TAHSILAT
--------------------------------------------------------

   CREATE SEQUENCE  "SYSTEM"."SEQ_TAHSILAT"  MINVALUE 100001 MAXVALUE 999999 INCREMENT BY 1 START WITH 200001 NOCACHE  NOORDER  CYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table BOS_ARAC_BILGILERI
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BOS_ARAC_BILGILERI" 
   (	"PLAKA" VARCHAR2(20 BYTE), 
	"MARKA" VARCHAR2(500 BYTE), 
	"TIP" VARCHAR2(500 BYTE), 
	"VITES" VARCHAR2(30 BYTE), 
	"YAKIT_TURU" VARCHAR2(15 BYTE), 
	"SON_KM" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BUTUN_ARAC_BILGILERI
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."BUTUN_ARAC_BILGILERI" 
   (	"PLAKA" VARCHAR2(20 BYTE), 
	"MARKA" VARCHAR2(500 BYTE), 
	"MODELI" NUMBER(*,0), 
	"VITES" VARCHAR2(30 BYTE), 
	"SON_KM" NUMBER(*,0), 
	"TIP" VARCHAR2(500 BYTE), 
	"YAKIT_TURU" VARCHAR2(15 BYTE), 
	"MUAYENE_TARIHI" DATE, 
	"SIGORTA_TARIHI" DATE, 
	"KASKO_TARIHI" DATE, 
	"ÞASI_NO" VARCHAR2(25 BYTE), 
	"MOTOR_NO" VARCHAR2(25 BYTE), 
	"RUHSAT_NO" VARCHAR2(25 BYTE), 
	"FILO_GIRIS_TARIHI" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FATURA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."FATURA" 
   (	"PLAKA" VARCHAR2(20 BYTE), 
	"MUSTERI_TC" VARCHAR2(100 BYTE), 
	"MUSTERI_AD" VARCHAR2(100 BYTE), 
	"MUSTERI_SOYAD" VARCHAR2(100 BYTE), 
	"MUSTERI_TEL_NO" VARCHAR2(11 BYTE), 
	"MUSTERI_SEHIR" VARCHAR2(100 BYTE), 
	"MUSTERI_ADRES" VARCHAR2(4000 BYTE), 
	"FATURA_NO" VARCHAR2(6 BYTE), 
	"GONDERIM_SEKLI" VARCHAR2(5 BYTE), 
	"TUTAR" NUMBER(38,0), 
	"KDV" NUMBER(38,2), 
	"ACIKLAMA" VARCHAR2(4000 BYTE), 
	"TARIH" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KAPANAN_SOZLESMELER
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."KAPANAN_SOZLESMELER" 
   (	"PLAKA" VARCHAR2(20 BYTE), 
	"MARKA" VARCHAR2(500 BYTE), 
	"TIP" VARCHAR2(500 BYTE), 
	"VITES" VARCHAR2(30 BYTE), 
	"BAS_KM" NUMBER(*,0), 
	"SON_KM" NUMBER(*,0), 
	"ARAC_FIYATI" NUMBER(*,0), 
	"KUR" VARCHAR2(20 BYTE), 
	"ODENEN_TOPLAM_MIKTAR" NUMBER(*,0), 
	"KDV_BEDELÝ" NUMBER(38,2), 
	"KIRALANAN_GUN_SAYISI" NUMBER(*,0), 
	"MUSTERI_TC" VARCHAR2(100 BYTE), 
	"MUSTERI_ADI" VARCHAR2(100 BYTE), 
	"MUSTERI_SOYADI" VARCHAR2(100 BYTE), 
	"TESLIM_EDEN" VARCHAR2(100 BYTE), 
	"TEL_NO" VARCHAR2(11 BYTE), 
	"BAS_TARIHI" DATE, 
	"BAS_SAATI" VARCHAR2(8 BYTE), 
	"BITIS_TARIHI" DATE, 
	"BITIS_SAATI" VARCHAR2(8 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KIRALANAN_ARAC_BILGILERI
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."KIRALANAN_ARAC_BILGILERI" 
   (	"PLAKA" VARCHAR2(20 BYTE), 
	"MARKA" VARCHAR2(500 BYTE), 
	"TIP" VARCHAR2(500 BYTE), 
	"VITES" VARCHAR2(30 BYTE), 
	"SON_KM" NUMBER(*,0), 
	"ARAC_FIYATI" NUMBER(*,0), 
	"KUR" VARCHAR2(20 BYTE), 
	"MUSTERI_TC" VARCHAR2(100 BYTE), 
	"MUSTERI_ADI" VARCHAR2(100 BYTE), 
	"MUSTERI_SOYADI" VARCHAR2(100 BYTE), 
	"TEL_NO" VARCHAR2(11 BYTE), 
	"BAS_TARIHI" DATE, 
	"BAS_SAATI" VARCHAR2(8 BYTE), 
	"BITIS_TARIHI" DATE, 
	"BITIS_SAATI" VARCHAR2(8 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KULLANICI
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."KULLANICI" 
   (	"ID" NUMBER(*,0) DEFAULT "SYSTEM"."SEQ_KULL"."NEXTVAL", 
	"ADI" VARCHAR2(100 BYTE), 
	"SOYADI" VARCHAR2(100 BYTE), 
	"NICK" VARCHAR2(100 BYTE), 
	"SIFRE" VARCHAR2(100 BYTE), 
	"YETKI" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MUSTERI_BILGILERI
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MUSTERI_BILGILERI" 
   (	"MUSTERI_TC" VARCHAR2(100 BYTE), 
	"AD" VARCHAR2(100 BYTE), 
	"SOYAD" VARCHAR2(100 BYTE), 
	"TEL_NO" VARCHAR2(11 BYTE), 
	"MAIL_ADD" VARCHAR2(200 BYTE), 
	"BAKIYE" NUMBER(*,0), 
	"ADRES" VARCHAR2(4000 BYTE), 
	"SEHIR" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MUSTERI_HESAP_EKS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."MUSTERI_HESAP_EKS" 
   (	"PLAKA" VARCHAR2(20 BYTE), 
	"ALACAK" NUMBER(*,0), 
	"BORC" NUMBER(*,0), 
	"TOTAL" NUMBER(*,0), 
	"MUSTERI_TC" VARCHAR2(100 BYTE), 
	"MUSTERI_ADI" VARCHAR2(100 BYTE), 
	"MUSTERI_SOYADI" VARCHAR2(100 BYTE), 
	"ACIKLAMA" VARCHAR2(4000 BYTE), 
	"TUR" VARCHAR2(100 BYTE), 
	"BAS_TARIHI" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ODEME
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ODEME" 
   (	"MUSTERI_TC" VARCHAR2(100 BYTE), 
	"MUSTERI_ADI" VARCHAR2(100 BYTE), 
	"MUSTERI_SOYADI" VARCHAR2(100 BYTE), 
	"PERSONEL" VARCHAR2(100 BYTE), 
	"MAKBUZ_NO" VARCHAR2(6 BYTE), 
	"KASA_TUTAR" NUMBER(38,2), 
	"CARI_TUTAR" NUMBER(38,2), 
	"ACIKLAMA" VARCHAR2(4000 BYTE), 
	"TARIH" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TAHSILAT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."TAHSILAT" 
   (	"MUSTERI_TC" VARCHAR2(100 BYTE), 
	"MUSTERI_ADI" VARCHAR2(100 BYTE), 
	"MUSTERI_SOYADI" VARCHAR2(100 BYTE), 
	"PERSONEL" VARCHAR2(100 BYTE), 
	"TAHSILAT_NO" VARCHAR2(6 BYTE), 
	"KASA_TUTAR" NUMBER(38,2), 
	"CARI_TUTAR" NUMBER(38,2), 
	"ACIKLAMA" VARCHAR2(4000 BYTE), 
	"TARIH" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for View MVIEW_EVALUATIONS
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."MVIEW_EVALUATIONS" ("RUNID", "MVIEW_OWNER", "MVIEW_NAME", "RANK", "STORAGE_IN_BYTES", "FREQUENCY", "CUMULATIVE_BENEFIT", "BENEFIT_TO_COST_RATIO") AS 
  select
  t1.runid# as runid,
  summary_owner AS mview_owner,
  summary_name AS mview_name,
  rank# as rank,
  storage_in_bytes,
  frequency,
  cumulative_benefit,
  benefit_to_cost_ratio
from SYSTEM.MVIEW$_ADV_OUTPUT t1, SYSTEM.MVIEW$_ADV_LOG t2, ALL_USERS u
where
  t1.runid# = t2.runid# and
  u.username = t2.uname and
  u.user_id = userenv('SCHEMAID') and
  t1.output_type = 1
order by t1.rank#;

   COMMENT ON TABLE "SYSTEM"."MVIEW_EVALUATIONS"  IS 'This view gives DBA access to summary evaluation output'
;
--------------------------------------------------------
--  DDL for View MVIEW_EXCEPTIONS
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."MVIEW_EXCEPTIONS" ("RUNID", "OWNER", "TABLE_NAME", "DIMENSION_NAME", "RELATIONSHIP", "BAD_ROWID") AS 
  select
  t1.runid# as runid,
  owner,
  table_name,
  dimension_name,
  relationship,
  bad_rowid
from SYSTEM.MVIEW$_ADV_EXCEPTIONS t1, SYSTEM.MVIEW$_ADV_LOG t2, ALL_USERS u
where
  t1.runid# = t2.runid# and
  u.username = t2.uname and
  u.user_id = userenv('SCHEMAID');

   COMMENT ON TABLE "SYSTEM"."MVIEW_EXCEPTIONS"  IS 'This view gives DBA access to dimension validation results'
;
--------------------------------------------------------
--  DDL for View MVIEW_FILTER
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."MVIEW_FILTER" ("FILTERID", "SUBFILTERNUM", "SUBFILTERTYPE", "STR_VALUE", "NUM_VALUE1", "NUM_VALUE2", "DATE_VALUE1", "DATE_VALUE2") AS 
  select
      a.filterid# as filterid,
      a.subfilternum# as subfilternum,
      decode(a.subfiltertype,1,'APPLICATION',2,'CARDINALITY',3,'LASTUSE',
                             4,'FREQUENCY',5,'USER',6,'PRIORITY',7,'BASETABLE',
                             8,'RESPONSETIME',9,'COLLECTIONID',10,'TRACENAME',
                             11,'SCHEMA','UNKNOWN') AS subfiltertype,
      a.str_value,
      to_number(decode(a.num_value1,-999,NULL,a.num_value1)) AS num_value1,
      to_number(decode(a.num_value2,-999,NULL,a.num_value2)) AS num_value2,
      a.date_value1,
      a.date_value2
   from system.mview$_adv_filter a, system.mview$_adv_log b, ALL_USERS u
   WHERE a.filterid# = b.runid#
   AND b.uname = u.username
   AND u.user_id = userenv('SCHEMAID');

   COMMENT ON TABLE "SYSTEM"."MVIEW_FILTER"  IS 'Workload filter records'
;
--------------------------------------------------------
--  DDL for View MVIEW_FILTERINSTANCE
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."MVIEW_FILTERINSTANCE" ("RUNID", "FILTERID", "SUBFILTERNUM", "SUBFILTERTYPE", "STR_VALUE", "NUM_VALUE1", "NUM_VALUE2", "DATE_VALUE1", "DATE_VALUE2") AS 
  select
      a.runid# as runid,
      a.filterid# as filterid,
      a.subfilternum# as subfilternum,
      decode(a.subfiltertype,1,'APPLICATION',2,'CARDINALITY',3,'LASTUSE',
                             4,'FREQUENCY',5,'USER',6,'PRIORITY',7,'BASETABLE',
                             8,'RESPONSETIME',9,'COLLECTIONID',10,'TRACENAME',
                             11,'SCHEMA','UNKNOWN') AS subfiltertype,
      a.str_value,
      to_number(decode(a.num_value1,-999,NULL,a.num_value1)) AS num_value1,
      to_number(decode(a.num_value2,-999,NULL,a.num_value2)) AS num_value2,
      a.date_value1,
      a.date_value2
   from system.mview$_adv_filterinstance a;

   COMMENT ON TABLE "SYSTEM"."MVIEW_FILTERINSTANCE"  IS 'Workload filter instance records'
;
--------------------------------------------------------
--  DDL for View MVIEW_LOG
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."MVIEW_LOG" ("ID", "FILTERID", "RUN_BEGIN", "RUN_END", "TYPE", "STATUS", "MESSAGE", "COMPLETED", "TOTAL", "ERROR_CODE") AS 
  select
      m.runid# as id,
      m.filterid# as filterid,
      m.run_begin,
      m.run_end,
      decode(m.run_type,1,'EVALUATE',2,'EVALUATE_W',3,'RECOMMEND',
                      4,'RECOMMEND_W',5,'VALIDATE',6,'WORKLOAD',
                      7,'FILTER','UNKNOWN') AS type,
      decode(m.status,0,'UNUSED',1,'CANCELLED',2,'IN_PROGRESS',3,'COMPLETED',
                    4,'ERROR','UNKNOWN') AS status,
      m.message,
      m.completed,
      m.total,
      m.error_code
   from system.mview$_adv_log m, all_users u
   where m.uname = u.username
   and   u.user_id = userenv('SCHEMAID');

   COMMENT ON TABLE "SYSTEM"."MVIEW_LOG"  IS 'Advisor session log'
;
--------------------------------------------------------
--  DDL for View MVIEW_RECOMMENDATIONS
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."MVIEW_RECOMMENDATIONS" ("RUNID", "ALL_TABLES", "FACT_TABLES", "GROUPING_LEVELS", "QUERY_TEXT", "RECOMMENDATION_NUMBER", "RECOMMENDED_ACTION", "MVIEW_OWNER", "MVIEW_NAME", "STORAGE_IN_BYTES", "PCT_PERFORMANCE_GAIN", "BENEFIT_TO_COST_RATIO") AS 
  select
  t1.runid# as runid,
  t1.from_clause as all_tables,
  fact_tables,
  grouping_levels,
  query_text,
  rank# as recommendation_number,
  action_type as recommended_action,
  summary_owner as mview_owner,
  summary_name as mview_name,
  storage_in_bytes,
  pct_performance_gain,
  benefit_to_cost_ratio
from SYSTEM.MVIEW$_ADV_OUTPUT t1, SYSTEM.MVIEW$_ADV_LOG t2, ALL_USERS u
where
  t1.runid# = t2.runid# and
  u.username = t2.uname and
  u.user_id = userenv('SCHEMAID') and
  t1.output_type = 0
order by t1.rank#;

   COMMENT ON TABLE "SYSTEM"."MVIEW_RECOMMENDATIONS"  IS 'This view gives DBA access to summary recommendations'
;
--------------------------------------------------------
--  DDL for View MVIEW_WORKLOAD
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."MVIEW_WORKLOAD" ("WORKLOADID", "IMPORT_TIME", "QUERYID", "APPLICATION", "CARDINALITY", "RESULTSIZE", "LASTUSE", "FREQUENCY", "OWNER", "PRIORITY", "QUERY", "RESPONSETIME") AS 
  select
  a.collectionid# as workloadid,
  a.collecttime as import_time,
  a.queryid# as queryid,
  a.application,
  a.cardinality,
  a.resultsize,
  a.qdate as lastuse,
  a.frequency,
  a.uname as owner,
  a.priority,
  a.sql_text as query,
  a.exec_time as responsetime
from SYSTEM.MVIEW$_ADV_WORKLOAD A, SYSTEM.MVIEW$_ADV_LOG B, ALL_USERS D
WHERE a.collectionid# = b.runid#
AND b.uname = d.username
AND d.user_id = userenv('SCHEMAID');

   COMMENT ON TABLE "SYSTEM"."MVIEW_WORKLOAD"  IS 'This view gives DBA access to shared workload'
;
--------------------------------------------------------
--  DDL for View OFISI_OLMAYANLAR
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."OFISI_OLMAYANLAR" ("STAFFNO", "FNAME", "LNAME", "FACULTY", "DEPARTMENT", "TITLE", "OFFICE", "YEARSWORKED", "SALARY", "PHONENMUM", "DOB") AS 
  SELECT "STAFFNO","FNAME","LNAME","FACULTY","DEPARTMENT","TITLE","OFFICE","YEARSWORKED","SALARY","PHONENMUM","DOB"
FROM STAFF
WHERE OFFICE IN (SELECT OFFICE
                FROM STAFF
                WHERE TITLE='Res. Asst.'
                GROUP BY OFFICE
                HAVING COUNT(OFFICE) > 1)
;
--------------------------------------------------------
--  DDL for View PRODUCT_PRIVS
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."PRODUCT_PRIVS" ("PRODUCT", "USERID", "ATTRIBUTE", "SCOPE", "NUMERIC_VALUE", "CHAR_VALUE", "DATE_VALUE", "LONG_VALUE") AS 
  SELECT PRODUCT, USERID, ATTRIBUTE, SCOPE,
         NUMERIC_VALUE, CHAR_VALUE, DATE_VALUE, LONG_VALUE
  FROM SQLPLUS_PRODUCT_PROFILE
  WHERE USERID = 'PUBLIC' OR
        USERID LIKE SYS_CONTEXT('USERENV','CURRENT_USER')
;
  GRANT READ ON "SYSTEM"."PRODUCT_PRIVS" TO PUBLIC;
--------------------------------------------------------
--  DDL for View SCHEDULER_JOB_ARGS
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."SCHEDULER_JOB_ARGS" ("OWNER", "JOB_NAME", "ARGUMENT_NAME", "ARGUMENT_POSITION", "ARGUMENT_TYPE", "VALUE", "ANYDATA_VALUE", "OUT_ARGUMENT") AS 
  SELECT "OWNER","JOB_NAME","ARGUMENT_NAME","ARGUMENT_POSITION","ARGUMENT_TYPE","VALUE","ANYDATA_VALUE","OUT_ARGUMENT" FROM sys.all_scheduler_job_args
;
  GRANT SELECT ON "SYSTEM"."SCHEDULER_JOB_ARGS" TO "SELECT_CATALOG_ROLE";
--------------------------------------------------------
--  DDL for View SCHEDULER_PROGRAM_ARGS
--------------------------------------------------------

  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "SYSTEM"."SCHEDULER_PROGRAM_ARGS" ("OWNER", "PROGRAM_NAME", "ARGUMENT_NAME", "ARGUMENT_POSITION", "ARGUMENT_TYPE", "METADATA_ATTRIBUTE", "DEFAULT_VALUE", "DEFAULT_ANYDATA_VALUE", "OUT_ARGUMENT") AS 
  SELECT "OWNER","PROGRAM_NAME","ARGUMENT_NAME","ARGUMENT_POSITION","ARGUMENT_TYPE","METADATA_ATTRIBUTE","DEFAULT_VALUE","DEFAULT_ANYDATA_VALUE","OUT_ARGUMENT" FROM sys.all_scheduler_program_args
;
  GRANT SELECT ON "SYSTEM"."SCHEDULER_PROGRAM_ARGS" TO "SELECT_CATALOG_ROLE";
REM INSERTING into SYSTEM.BOS_ARAC_BILGILERI
SET DEFINE OFF;
REM INSERTING into SYSTEM.BUTUN_ARAC_BILGILERI
SET DEFINE OFF;
REM INSERTING into SYSTEM.FATURA
SET DEFINE OFF;
REM INSERTING into SYSTEM.KAPANAN_SOZLESMELER
SET DEFINE OFF;
REM INSERTING into SYSTEM.KIRALANAN_ARAC_BILGILERI
SET DEFINE OFF;
REM INSERTING into SYSTEM.KULLANICI
SET DEFINE OFF;
REM INSERTING into SYSTEM.MUSTERI_BILGILERI
SET DEFINE OFF;
REM INSERTING into SYSTEM.MUSTERI_HESAP_EKS
SET DEFINE OFF;
REM INSERTING into SYSTEM.ODEME
SET DEFINE OFF;
REM INSERTING into SYSTEM.TAHSILAT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Trigger BOS_EKLEME
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."BOS_EKLEME" 
BEFORE DELETE OR INSERT OR UPDATE ON BUTUN_ARAC_BILGILERI 
FOR EACH ROW

BEGIN
    CASE
    WHEN INSERTING THEN
    INSERT INTO BOS_ARAC_BILGILERI VALUES (:NEW.PLAKA, :NEW.MARKA, :NEW.TIP, :NEW.VITES, :NEW.YAKIT_TURU, :NEW.SON_KM);
    
    WHEN UPDATING THEN
    UPDATE BOS_ARAC_BILGILERI
    SET SON_KM = :NEW.SON_KM
    WHERE PLAKA = :OLD.PLAKA;
    
    WHEN DELETING THEN
    NULL;
    
    END CASE;
END;
/
ALTER TRIGGER "SYSTEM"."BOS_EKLEME" ENABLE;
--------------------------------------------------------
--  DDL for Trigger KIRALIK_SILME
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."KIRALIK_SILME" 
AFTER INSERT OR DELETE ON KIRALANAN_ARAC_BILGILERI 

FOR EACH ROW 

BEGIN
    CASE
        WHEN INSERTING THEN
        
            DELETE FROM BOS_ARAC_BILGILERI WHERE PLAKA = :NEW.PLAKA;
            
        WHEN DELETING THEN   
        
            
            INSERT INTO BOS_ARAC_BILGILERI SELECT PLAKA, MARKA, TIP, VITES, YAKIT_TURU, SON_KM FROM BUTUN_ARAC_BILGILERI WHERE PLAKA = :OLD.PLAKA;
           
    END CASE; 
END;
/
ALTER TRIGGER "SYSTEM"."KIRALIK_SILME" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BOS_EKLEME
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."BOS_EKLEME" 
BEFORE DELETE OR INSERT OR UPDATE ON BUTUN_ARAC_BILGILERI 
FOR EACH ROW

BEGIN
    CASE
    WHEN INSERTING THEN
    INSERT INTO BOS_ARAC_BILGILERI VALUES (:NEW.PLAKA, :NEW.MARKA, :NEW.TIP, :NEW.VITES, :NEW.YAKIT_TURU, :NEW.SON_KM);
    
    WHEN UPDATING THEN
    UPDATE BOS_ARAC_BILGILERI
    SET SON_KM = :NEW.SON_KM
    WHERE PLAKA = :OLD.PLAKA;
    
    WHEN DELETING THEN
    NULL;
    
    END CASE;
END;
/
ALTER TRIGGER "SYSTEM"."BOS_EKLEME" ENABLE;
--------------------------------------------------------
--  DDL for Trigger KIRALIK_SILME
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "SYSTEM"."KIRALIK_SILME" 
AFTER INSERT OR DELETE ON KIRALANAN_ARAC_BILGILERI 

FOR EACH ROW 

BEGIN
    CASE
        WHEN INSERTING THEN
        
            DELETE FROM BOS_ARAC_BILGILERI WHERE PLAKA = :NEW.PLAKA;
            
        WHEN DELETING THEN   
        
            
            INSERT INTO BOS_ARAC_BILGILERI SELECT PLAKA, MARKA, TIP, VITES, YAKIT_TURU, SON_KM FROM BUTUN_ARAC_BILGILERI WHERE PLAKA = :OLD.PLAKA;
           
    END CASE; 
END;
/
ALTER TRIGGER "SYSTEM"."KIRALIK_SILME" ENABLE;
--------------------------------------------------------
--  DDL for Procedure ARACKIRALAMA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."ARACKIRALAMA" 
(
  IN_PLAKA_BILGISI IN VARCHAR,
  IN_MARKA IN VARCHAR,
  IN_TIP IN VARCHAR,
  IN_SON_KM IN int,
  IN_VITES IN VARCHAR,
  IN_MUSTERI_TC IN VARCHAR,
  IN_MUSTERI_ADI IN VARCHAR,
  IN_MUSTERI_SOYADI IN VARCHAR,
  IN_BAS_TAR IN DATE,
  IN_BAS_SA IN VARCHAR,
  IN_BIT_TAR IN DATE,
  IN_BIT_SA IN VARCHAR,
  IN_ARAC_FIYATI int,
  IN_KUR IN VARCHAR
) AS 
    
    TEL_NO2 VARCHAR(11);
    TEMP_GUN_FARKI NUMBER;
    TEMP_TOPLAM_PARA NUMBER;
    TEMP_BORC NUMBER;
    TEMP_TOTAL NUMBER;
    
BEGIN
    
    SELECT TEL_NO INTO TEL_NO2 FROM MUSTERI_BILGILERI WHERE MUSTERI_TC = IN_MUSTERI_TC;
        
    
    INSERT INTO KIRALANAN_ARAC_BILGILERI VALUES (IN_PLAKA_BILGISI, IN_MARKA, IN_TIP,IN_VITES,IN_SON_KM, IN_ARAC_FIYATI,IN_KUR, 
    IN_MUSTERI_TC, IN_MUSTERI_ADI, IN_MUSTERI_SOYADI, TEL_NO2, IN_BAS_TAR, IN_BAS_SA, IN_BIT_TAR, IN_BIT_SA );
    
    TEMP_GUN_FARKI := TRUNC(IN_BIT_TAR) - TRUNC(IN_BAS_TAR);
    TEMP_TOPLAM_PARA := IN_ARAC_FIYATI * TEMP_GUN_FARKI;
    
    UPDATE MUSTERI_BILGILERI SET BAKIYE = BAKIYE+TEMP_TOPLAM_PARA WHERE MUSTERI_TC = IN_MUSTERI_TC;
    SELECT BAKIYE INTO TEMP_TOTAL FROM MUSTERI_BILGILERI WHERE MUSTERI_TC = IN_MUSTERI_TC;
    

    INSERT INTO MUSTERI_HESAP_EKS (PLAKA,ALACAK,BORC,TOTAL,MUSTERI_TC,MUSTERI_ADI,MUSTERI_SOYADI,ACIKLAMA,BAS_TARIHI,TUR)
    VALUES (IN_PLAKA_BILGISI,0, TEMP_TOPLAM_PARA, TEMP_TOPLAM_PARA, IN_MUSTERI_TC, IN_MUSTERI_ADI, IN_MUSTERI_SOYADI, 'FATURA KESÝLMEDÝ', IN_BIT_TAR, 'KÝRALAMA');
    
   
    
    
    
END ARACKIRALAMA;

/
--------------------------------------------------------
--  DDL for Procedure FATURA_PRO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."FATURA_PRO" 
(
  IN_PLAKA IN VARCHAR2 
, IN_TC IN VARCHAR2 
, IN_AD IN VARCHAR2 
, IN_SOYAD IN VARCHAR2 
, IN_TELNO IN VARCHAR2 
, IN_SEHIR IN VARCHAR2 
, IN_ADRES IN VARCHAR2 
, IN_FATURA_NO IN VARCHAR2 
, IN_GONDERIMSEKLI IN VARCHAR2 
, IN_KDV IN VARCHAR2 
, IN_GENEL_TOPLAM IN VARCHAR2 
, IN_ACIKLAMA IN VARCHAR2 
, IN_TARIH IN VARCHAR2 
) AS 

TEMP_TOTAL NUMBER;

BEGIN
    INSERT INTO FATURA VALUES (IN_PLAKA,IN_TC,IN_AD,IN_SOYAD,IN_TELNO,IN_SEHIR,IN_ADRES,IN_FATURA_NO,IN_GONDERIMSEKLI,IN_KDV,IN_GENEL_TOPLAM,IN_ACIKLAMA,IN_TARIH);
    
    SELECT BAKIYE INTO TEMP_TOTAL FROM MUSTERI_BILGILERI WHERE MUSTERI_TC = IN_TC;
    
    UPDATE MUSTERI_HESAP_EKS SET ACIKLAMA =IN_ACIKLAMA, TOTAL = TEMP_TOTAL  WHERE (MUSTERI_TC = IN_TC and PLAKA = IN_PLAKA and ACIKLAMA = 'FATURA KESÝLMEDÝ');
    
END FATURA_PRO;

/
--------------------------------------------------------
--  DDL for Procedure GIRIS_PROCEDURE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."GIRIS_PROCEDURE" 
(
  IN_NICK IN VARCHAR2 
, IN_SIFRE IN VARCHAR2 
, OUT_SONUC OUT VARCHAR2
, OUT_YETKI OUT VARCHAR2
, OUT_AD OUT VARCHAR2
, OUT_SOYAD OUT VARCHAR2
) AS 

TEMP_NICK VARCHAR(100);
TEMP_SIFRE VARCHAR(100);

BEGIN
  
  
  SELECT NICK INTO TEMP_NICK FROM KULLANICI WHERE (NICK = IN_NICK) and (SIFRE = IN_SIFRE);
  SELECT SIFRE INTO TEMP_SIFRE FROM KULLANICI WHERE (NICK = IN_NICK) and (SIFRE = IN_SIFRE);
  
  
  
  IF IN_NICK = TEMP_NICK and IN_SIFRE = TEMP_SIFRE THEN
    OUT_SONUC := 'GIRIS_BASARILI';
    
  ELSIF  IN_NICK = TEMP_NICK and IN_SIFRE != TEMP_SIFRE THEN
    OUT_SONUC := 'SIFRE_YANLIS';
  ELSIF  IN_NICK != TEMP_NICK and IN_SIFRE = TEMP_SIFRE THEN
    OUT_SONUC := 'NICK_YANLIS';
  ELSE
    OUT_SONUC := 'IKISI_DE_YANLIS';
  
  END IF;
  
  
  IF (OUT_SONUC = 'GIRIS_BASARILI') THEN
    SELECT YETKI INTO OUT_YETKI FROM KULLANICI WHERE (NICK = IN_NICK) and (SIFRE = IN_SIFRE);
    SELECT ADI INTO OUT_AD FROM KULLANICI WHERE (NICK = IN_NICK) and (SIFRE = IN_SIFRE);
    SELECT SOYADI INTO OUT_SOYAD FROM KULLANICI WHERE (NICK = IN_NICK) and (SIFRE = IN_SIFRE);
    
  ELSE 
    NULL;
    
  END IF;
  
END GIRIS_PROCEDURE;

/
--------------------------------------------------------
--  DDL for Procedure KONTRAT_KALDIR
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."KONTRAT_KALDIR" 
(
  IN_PLAKA IN VARCHAR2 
, IN_MUSTERI_TC IN VARCHAR2
, IN_DONUS_KM IN NUMBER
, IN_KDV IN NUMBER
, IN_TESLIM_EDEN IN VARCHAR2
, IN_DONUS_TARIHI IN DATE
, IN_KDON_TIME IN VARCHAR2

) AS 
 
TEMP_BAS_TAR DATE;
TEMP_GUN_FARKI NUMBER;
TEMP_ARAC_FIYATI NUMBER;
TEMP_TELNO VARCHAR2(11);
TEMP_TOPLAM_PARA NUMBER;

BEGIN

    SELECT BAS_TARIHI INTO TEMP_BAS_TAR FROM KIRALANAN_ARAC_BILGILERI WHERE PLAKA = IN_PLAKA;
    
    
    TEMP_GUN_FARKI := TRUNC(IN_DONUS_TARIHI) - TRUNC(TEMP_BAS_TAR);
    
    
    SELECT ARAC_FIYATI INTO TEMP_ARAC_FIYATI FROM KIRALANAN_ARAC_BILGILERI WHERE PLAKA = IN_PLAKA;
    
    TEMP_TOPLAM_PARA := TEMP_ARAC_FIYATI * TEMP_GUN_FARKI;
    
    
    
    SELECT TEL_NO INTO TEMP_TELNO FROM MUSTERI_BILGILERI WHERE MUSTERI_TC = IN_MUSTERI_TC;
    
    
    
    INSERT INTO KAPANAN_SOZLESMELER (PLAKA,MARKA,TIP,VITES,BAS_KM,ARAC_FIYATI,KUR,MUSTERI_TC,MUSTERI_ADI,MUSTERI_SOYADI,BAS_TARIHI,BAS_SAATI)
    SELECT PLAKA,MARKA,TIP,VITES,SON_KM,ARAC_FIYATI,KUR,MUSTERI_TC,MUSTERI_ADI,MUSTERI_SOYADI,BAS_TARIHI,BAS_SAATI 
    FROM KIRALANAN_ARAC_BILGILERI WHERE PLAKA=IN_PLAKA;
    
    UPDATE KAPANAN_SOZLESMELER SET 
    SON_KM = IN_DONUS_KM,
    ODENEN_TOPLAM_MIKTAR = TEMP_TOPLAM_PARA,
    KDV_BEDELÝ = IN_KDV,
    KIRALANAN_GUN_SAYISI = TEMP_GUN_FARKI,
    TESLIM_EDEN = IN_TESLIM_EDEN,
    TEL_NO = TEMP_TELNO,
    BITIS_TARIHI = IN_DONUS_TARIHI,
    BITIS_SAATI = IN_KDON_TIME
    WHERE PLAKA = IN_PLAKA;
    
    
    
    
    DELETE FROM KIRALANAN_ARAC_BILGILERI WHERE PLAKA = IN_PLAKA;
    
    UPDATE BUTUN_ARAC_BILGILERI
    SET SON_KM = IN_DONUS_KM
    WHERE PLAKA = IN_PLAKA;
    
    
    
    
    
END KONTRAT_KALDIR;

/
--------------------------------------------------------
--  DDL for Procedure ODEME_PRO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."ODEME_PRO" 
(
  IN_TC IN VARCHAR2 
, IN_AD IN VARCHAR2 
, IN_SOYAD IN VARCHAR2 
, IN_PERSONEL IN VARCHAR2 
, IN_MAKBUZ_NO IN VARCHAR2 
, IN_KASA_TUTARI IN VARCHAR2 
, IN_CARI_TUTAR IN VARCHAR2 
, IN_ACIKLAMA IN VARCHAR2 
, IN_TARIH IN VARCHAR2 
) AS 

TEMP_TUTAR NUMBER;

BEGIN
  
    INSERT INTO ODEME VALUES (IN_TC,IN_AD,IN_SOYAD,IN_PERSONEL,IN_MAKBUZ_NO,IN_KASA_TUTARI,IN_CARI_TUTAR,IN_ACIKLAMA,IN_TARIH);
    
    UPDATE MUSTERI_BILGILERI SET BAKIYE = BAKIYE  + IN_CARI_TUTAR WHERE MUSTERI_TC = IN_TC;
    
    SELECT BAKIYE INTO TEMP_TUTAR FROM MUSTERI_BILGILERI WHERE MUSTERI_TC = IN_TC;
    
    INSERT INTO MUSTERI_HESAP_EKS(ALACAK,BORC,TOTAL,MUSTERI_TC,MUSTERI_ADI,MUSTERI_SOYADI,ACIKLAMA,TUR,BAS_TARIHI) 
    VALUES (0,IN_CARI_TUTAR,TEMP_TUTAR,IN_TC,IN_AD,IN_SOYAD,IN_ACIKLAMA,'TAHSÝLAT',IN_TARIH);
    
    
    
END ODEME_PRO;

/
--------------------------------------------------------
--  DDL for Procedure TAHSILAT_PRO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "SYSTEM"."TAHSILAT_PRO" 
(
  IN_TC IN VARCHAR2 
, IN_AD IN VARCHAR2 
, IN_SOYAD IN VARCHAR2 
, IN_PERSONEL IN VARCHAR2 
, IN_TAHSILAT_NO IN VARCHAR2 
, IN_KASA_TUTARI IN VARCHAR2 
, IN_CARI_TUTAR IN VARCHAR2 
, IN_ACIKLAMA IN VARCHAR2 
, IN_TARIH IN VARCHAR2 
) AS 

TEMP_TUTAR NUMBER;

BEGIN

    INSERT INTO TAHSILAT VALUES (IN_TC,IN_AD,IN_SOYAD,IN_PERSONEL,IN_TAHSILAT_NO,IN_KASA_TUTARI,IN_CARI_TUTAR,IN_ACIKLAMA,IN_TARIH);
    UPDATE MUSTERI_BILGILERI SET BAKIYE = BAKIYE  - IN_CARI_TUTAR WHERE MUSTERI_TC = IN_TC;
    
    SELECT BAKIYE INTO TEMP_TUTAR FROM MUSTERI_BILGILERI WHERE MUSTERI_TC = IN_TC;
    
    INSERT INTO MUSTERI_HESAP_EKS(ALACAK,BORC,TOTAL,MUSTERI_TC,MUSTERI_ADI,MUSTERI_SOYADI,ACIKLAMA,TUR,BAS_TARIHI) 
    VALUES (IN_CARI_TUTAR,0,TEMP_TUTAR,IN_TC,IN_AD,IN_SOYAD,IN_ACIKLAMA,'TAHSÝLAT',IN_TARIH);
    
    
  
END TAHSILAT_PRO;

/
--------------------------------------------------------
--  Constraints for Table BOS_ARAC_BILGILERI
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BOS_ARAC_BILGILERI" MODIFY ("PLAKA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BOS_ARAC_BILGILERI" ADD PRIMARY KEY ("PLAKA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BUTUN_ARAC_BILGILERI
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."BUTUN_ARAC_BILGILERI" MODIFY ("PLAKA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."BUTUN_ARAC_BILGILERI" ADD PRIMARY KEY ("PLAKA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FATURA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."FATURA" MODIFY ("MUSTERI_TC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KAPANAN_SOZLESMELER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."KAPANAN_SOZLESMELER" MODIFY ("PLAKA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."KAPANAN_SOZLESMELER" MODIFY ("MUSTERI_ADI" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."KAPANAN_SOZLESMELER" MODIFY ("MUSTERI_SOYADI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KIRALANAN_ARAC_BILGILERI
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."KIRALANAN_ARAC_BILGILERI" MODIFY ("PLAKA" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."KIRALANAN_ARAC_BILGILERI" MODIFY ("MUSTERI_ADI" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."KIRALANAN_ARAC_BILGILERI" MODIFY ("MUSTERI_SOYADI" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."KIRALANAN_ARAC_BILGILERI" ADD PRIMARY KEY ("PLAKA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KULLANICI
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."KULLANICI" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."KULLANICI" MODIFY ("NICK" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."KULLANICI" MODIFY ("SIFRE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."KULLANICI" MODIFY ("YETKI" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."KULLANICI" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MUSTERI_BILGILERI
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MUSTERI_BILGILERI" MODIFY ("MUSTERI_TC" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MUSTERI_BILGILERI" ADD PRIMARY KEY ("MUSTERI_TC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MUSTERI_HESAP_EKS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."MUSTERI_HESAP_EKS" MODIFY ("MUSTERI_ADI" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."MUSTERI_HESAP_EKS" MODIFY ("MUSTERI_SOYADI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ODEME
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ODEME" MODIFY ("MUSTERI_TC" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ODEME" MODIFY ("MUSTERI_ADI" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ODEME" MODIFY ("MUSTERI_SOYADI" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ODEME" MODIFY ("PERSONEL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TAHSILAT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."TAHSILAT" MODIFY ("MUSTERI_TC" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TAHSILAT" MODIFY ("MUSTERI_ADI" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TAHSILAT" MODIFY ("MUSTERI_SOYADI" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."TAHSILAT" MODIFY ("PERSONEL" NOT NULL ENABLE);
