/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;


import bilgiler.ButunAracBilgileri;
import db_islemler.ButunDBIslemleri;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sudeg
 */
public class ButunAracListeleme extends javax.swing.JPanel {
    
    ButunDBIslemleri islemler = new ButunDBIslemleri();
    DefaultTableModel modelim3 = new DefaultTableModel();

    /**
     * Creates new form ButunAracListeleme2
     */
    public ButunAracListeleme() {
        initComponents();
        
        
        modelim3 = (DefaultTableModel) butunAraclarTablo.getModel();
        modelim3.setRowCount(0);
        ArrayList<ButunAracBilgileri> butun_array = new ArrayList<ButunAracBilgileri>();
        butun_array = islemler.butunArac_listele();
        if (butun_array != null){
            
            for (ButunAracBilgileri butun : butun_array){
                Object[] eklenenler = { butun.getPlaka(),butun.getMarka(),butun.getModel(),butun.getTipi(),butun.getVites(),
                    butun.getSon_km(),butun.getYakit_turu(),butun.getSasi_no(),butun.getMotor_no(),butun.getRuhsat_belge_no(),
                    butun.getMuayene(),butun.getSigorta(),butun.getKasko(),butun.getFilo_giris_tarihi()};
                
                modelim3.addRow(eklenenler);
                
            }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        butunAraclarTablo = new javax.swing.JTable();
        butun_araclar = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        butunAraclarTablo.setBackground(new java.awt.Color(255, 255, 255));
        butunAraclarTablo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        butunAraclarTablo.setForeground(new java.awt.Color(0, 0, 204));
        butunAraclarTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "PLAKA", "MARKA", "MODEL", "TİP", "VİTES", "SON KM", "YAKIT TÜRÜ", "ŞASİ NO", "MOTOR NO", "RUHSAT NO", "MUAYENE TARİHİ", "SİGORTA TARİHİ", "KASKO TARİHİ", "FİLO GİRİŞ TARİHİ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        butunAraclarTablo.setSelectionBackground(new java.awt.Color(153, 153, 255));
        butunAraclarTablo.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(butunAraclarTablo);

        butun_araclar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        butun_araclar.setForeground(new java.awt.Color(153, 153, 255));
        butun_araclar.setText("BÜTÜN ARAÇLARIN LİSTESİ");

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setText("Plakaya Göre Sırala");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 94, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(butun_araclar, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox1)
                .addGap(340, 340, 340))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(butun_araclar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        
        modelim3.setRowCount(0);
        
        modelim3 = (DefaultTableModel) butunAraclarTablo.getModel();
        modelim3.setRowCount(0);
        ArrayList<ButunAracBilgileri> butun_array = new ArrayList<ButunAracBilgileri>();
        butun_array = islemler.plaka_sirala_butunArac_listele();
        if (butun_array != null){
            
            for (ButunAracBilgileri butun : butun_array){
                Object[] eklenenler = { butun.getPlaka(),butun.getMarka(),butun.getModel(),butun.getTipi(),butun.getVites(),
                    butun.getSon_km(),butun.getYakit_turu(),butun.getSasi_no(),butun.getMotor_no(),butun.getRuhsat_belge_no(),
                    butun.getMuayene(),butun.getSigorta(),butun.getKasko(),butun.getFilo_giris_tarihi()};
                
                modelim3.addRow(eklenenler);
                
            }
        }
        
        
        if(!jCheckBox1.isSelected()){
            
            modelim3.setRowCount(0);
            
            butun_array = islemler.butunArac_listele();
            if (butun_array != null){
            
                for (ButunAracBilgileri butun : butun_array){
                    Object[] eklenenler = { butun.getPlaka(),butun.getMarka(),butun.getModel(),butun.getTipi(),butun.getVites(),
                        butun.getSon_km(),butun.getYakit_turu(),butun.getSasi_no(),butun.getMotor_no(),butun.getRuhsat_belge_no(),
                        butun.getMuayene(),butun.getSigorta(),butun.getKasko(),butun.getFilo_giris_tarihi()};
                
                    modelim3.addRow(eklenenler);
                
                }
            }
        
            
        }
        
        
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable butunAraclarTablo;
    private javax.swing.JLabel butun_araclar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
