/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;


import bilgiler.KiralananAracBilgileri;
import db_islemler.ButunDBIslemleri;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sudeg
 */
public class Fatura extends javax.swing.JFrame {
    
    ButunDBIslemleri islemler = new ButunDBIslemleri();
    DefaultTableModel modelim1 = new DefaultTableModel();
    String plaka;
    

    /**
     * Creates new form Fatura2
     */
    public Fatura(String temp_musteriAd,String temp_musteriSoyad,String temp_musteriTC,
    String temp_tel_no,String temp_adres, String temp_sehir) {
        
        initComponents();
        
        cari_ad.setBorder(BorderFactory.createLineBorder(Color.decode("#2C6791")));
        fatura_no_txt.setBorder(BorderFactory.createLineBorder(Color.decode("#2C6791")));
        cari_soyad.setBorder(BorderFactory.createLineBorder(Color.decode("#2C6791")));
        cari_tc.setBorder(BorderFactory.createLineBorder(Color.decode("#2C6791")));
        fatura_saati.setBorder(BorderFactory.createLineBorder(Color.decode("#2C6791")));
        adres_txt.setBorder(BorderFactory.createLineBorder(Color.decode("#2C6791")));
        sehir_txt.setBorder(BorderFactory.createLineBorder(Color.decode("#2C6791")));
        telno_txt.setBorder(BorderFactory.createLineBorder(Color.decode("#2C6791")));
        aciklama_txt.setBorder(BorderFactory.createLineBorder(Color.decode("#2C6791")));
        kdv_haric_txt.setBorder(BorderFactory.createLineBorder(Color.decode("#2C6791")));
        kdv_txt.setBorder(BorderFactory.createLineBorder(Color.decode("#2C6791")));
        kdv_dahil_txt.setBorder(BorderFactory.createLineBorder(Color.decode("#2C6791")));
        
        
        
        
        aciklama_txt.setLineWrap(true);
        adres_txt.setLineWrap(true);
        
        
        fatura_no_txt.setText(String.valueOf(islemler.seq_fatura()));
        
        
        cari_ad.setText(temp_musteriAd);
        cari_soyad.setText(temp_musteriSoyad);
        cari_tc.setText(temp_musteriTC);
        adres_txt.setText(temp_adres);
        sehir_txt.setText(temp_sehir);
        telno_txt.setText(temp_tel_no);
        
        
        modelim1 = (DefaultTableModel) kiralik_arac_table2.getModel();
        modelim1.setRowCount(0);
        ArrayList<KiralananAracBilgileri> kiralik_array = new ArrayList<KiralananAracBilgileri>();
        kiralik_array = islemler.carinin_arac_listesi(temp_musteriTC);
        if (kiralik_array != null){
            
            for (KiralananAracBilgileri kiralik : kiralik_array){
                Object[] eklenenler = { kiralik.getPlaka(),kiralik.getMarka(),kiralik.getArac_fiyati(),kiralik.getBaslangic_tarihi(),kiralik.getBitis_tarihi()};
                
                modelim1.addRow(eklenenler);
                
            }
        }
        
        setDefaultCloseOperation(Fatura.DISPOSE_ON_CLOSE);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cari_ad = new javax.swing.JTextField();
        cari_soyad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sehir_txt = new javax.swing.JTextField();
        telno_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cari_tc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fatura_no_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fatura_tarih = new org.jdesktop.swingx.JXDatePicker();
        jLabel8 = new javax.swing.JLabel();
        Date date = new Date();
        SpinnerDateModel sm = new SpinnerDateModel(date, null, null, Calendar.HOUR_OF_DAY);
        fatura_saati = new javax.swing.JSpinner(sm);
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        kiralik_arac_table2 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        aciklama_txt = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        adres_txt = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        gonderim_sekli_combobox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        kdv = new javax.swing.JLabel();
        kdv_dahil_txt = new javax.swing.JTextField();
        kdv_txt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        kdv_haric_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CARİ AD");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CARİ SOYAD");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ADRES");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ŞEHİR/TEL NO");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("CARİ TC");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("FATURA NO");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("TARİH");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("SAAT");

        JSpinner.DateEditor de = new JSpinner.DateEditor(fatura_saati, "HH:mm:ss");
        fatura_saati.setEditor(de);

        kiralik_arac_table2.setBackground(new java.awt.Color(255, 255, 255));
        kiralik_arac_table2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kiralik_arac_table2.setForeground(new java.awt.Color(0, 0, 204));
        kiralik_arac_table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Plaka", "Marka", "Fiyatı", "Baş.Tar.", "Bitiş Tar."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        kiralik_arac_table2.setSelectionBackground(new java.awt.Color(153, 153, 255));
        kiralik_arac_table2.setSelectionForeground(new java.awt.Color(255, 255, 255));
        kiralik_arac_table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                kiralik_arac_table2MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(kiralik_arac_table2);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("AÇIKLAMA");

        aciklama_txt.setColumns(20);
        aciklama_txt.setRows(5);
        jScrollPane2.setViewportView(aciklama_txt);

        adres_txt.setColumns(20);
        adres_txt.setRows(5);
        jScrollPane3.setViewportView(adres_txt);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("GÖNDERİM ŞEKLİ");

        gonderim_sekli_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "POSTA", "EMAIL" }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("KDV DAHİL TOPLAM");

        kdv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kdv.setForeground(new java.awt.Color(0, 0, 0));
        kdv.setText("KDV");

        kdv_txt.setEditable(false);

        jButton1.setText("FATURALA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("KDV HARİÇ TOPLAM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cari_soyad)
                                    .addComponent(cari_tc)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(sehir_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(telno_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane3)))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(cari_ad)))
                        .addGap(114, 114, 114)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fatura_saati)
                            .addComponent(fatura_no_txt)
                            .addComponent(fatura_tarih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2))
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gonderim_sekli_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(212, 212, 212)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kdv, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kdv_haric_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kdv_dahil_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kdv_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cari_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(fatura_no_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cari_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(fatura_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cari_tc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(fatura_saati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sehir_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telno_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gonderim_sekli_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(kdv_haric_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kdv)
                    .addComponent(kdv_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kdv_dahil_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kiralik_arac_table2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kiralik_arac_table2MouseReleased
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            
            int row = kiralik_arac_table2.getSelectedRow();

            if(row>=0){
                String temp_plaka = kiralik_arac_table2.getValueAt(row, 0).toString();
                ArrayList<KiralananAracBilgileri> bir_kiralik_array = new ArrayList<KiralananAracBilgileri>();
                bir_kiralik_array = islemler.arac_bilgileri(temp_plaka);
                
                for (KiralananAracBilgileri kiralik : bir_kiralik_array){
                    Object[] bilgiler = { kiralik.getArac_fiyati(),kiralik.getBaslangic_tarihi(),kiralik.getBitis_tarihi()};
                    int fiyat = (int) bilgiler[0];
                    Date bas_tar = (Date) bilgiler[1];
                    Date bit_tar = (Date) bilgiler[2];
                
                    long gun_farkı = bit_tar.getTime() - bas_tar.getTime() ;  
                    gun_farkı = (gun_farkı / (1000 * 60 * 60 * 24));
                
                    Integer ara_toplam = fiyat * (int) gun_farkı;
                
                    kdv_dahil_txt.setText(ara_toplam.toString());
                
                
                
                    double kdv = ara_toplam * 0.18;
                
                    kdv_txt.setText(String.valueOf(kdv));
                    
                    
                    double kdv_haric = ara_toplam - kdv;
                    
                    
                    kdv_haric_txt.setText(String.valueOf(kdv_haric));
                
                    
                
                }
            }
            
            this.plaka = String.valueOf(kiralik_arac_table2.getValueAt(row,0));
            
        }
    }//GEN-LAST:event_kiralik_arac_table2MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String musteriTC = cari_tc.getText();
        String musteriAd = cari_ad.getText();
        String musteriSoyad = cari_soyad.getText(); 
        String tel_no = telno_txt.getText();
        String adres = adres_txt.getText();
        String sehir = sehir_txt.getText(); 
        String fatura_no = fatura_no_txt.getText();
        String gonderim_sekli = gonderim_sekli_combobox.getSelectedItem().toString();
        String kdv_dahil = kdv_dahil_txt.getText();  
        String kdvv = kdv_txt.getText();
        String aciklama = aciklama_txt.getText();
        String kdv_haric =  kdv_haric_txt.getText();
        
        java.util.Date util_tarih = new java.util.Date();
        util_tarih = fatura_tarih.getDate();
        java.sql.Date tarih2 = new java.sql.Date(util_tarih.getTime()); //islemler için
        
        DateFormat dateFormat = new SimpleDateFormat("DD/MM/YY");  
        String tarih = dateFormat.format(tarih2);  //fatura classı için
        
        int kdv_dahil2 = Integer.parseInt(kdv_dahil_txt.getText());  //fatura classı için
        Double kdvv2 = Double.parseDouble(kdv_txt.getText()); //fatura classı için
        
        
        islemler.fatura_ekle(musteriTC, musteriAd, musteriSoyad, tel_no, adres, sehir, fatura_no, 
               gonderim_sekli, kdv_dahil2, kdvv2, aciklama, this.plaka, tarih2);
        
          
        
        
        new FaturaGoruntule(musteriTC,musteriAd,musteriSoyad,tel_no,adres,sehir,fatura_no,
                gonderim_sekli,kdv_dahil,kdvv,aciklama,tarih,kdv_haric).setVisible(true);
        
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fatura(null,null,null,null,null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea aciklama_txt;
    private javax.swing.JTextArea adres_txt;
    private javax.swing.JTextField cari_ad;
    private javax.swing.JTextField cari_soyad;
    private javax.swing.JTextField cari_tc;
    private javax.swing.JTextField fatura_no_txt;
    private javax.swing.JSpinner fatura_saati;
    private org.jdesktop.swingx.JXDatePicker fatura_tarih;
    private javax.swing.JComboBox<String> gonderim_sekli_combobox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel kdv;
    private javax.swing.JTextField kdv_dahil_txt;
    private javax.swing.JTextField kdv_haric_txt;
    private javax.swing.JTextField kdv_txt;
    private javax.swing.JTable kiralik_arac_table2;
    private javax.swing.JTextField sehir_txt;
    private javax.swing.JTextField telno_txt;
    // End of variables declaration//GEN-END:variables
}
