/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import bilgiler.KontratBilgileri;
import db_islemler.ButunDBIslemleri;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author sudeg
 */
public class KapananSozlesmeler extends javax.swing.JPanel {
    
    
    ButunDBIslemleri islemler = new ButunDBIslemleri();
    DefaultTableModel modelim2 = new DefaultTableModel();

    /**
     * Creates new form KapananSozlesmeler
     */
    public KapananSozlesmeler() {
        initComponents();
        musteriAramaYeri.setBorder(BorderFactory.createLineBorder(Color.decode("#2C6791")));
        modelim2 = (DefaultTableModel) sozlesme_table.getModel();
        modelim2.setRowCount(0);
        ArrayList<KontratBilgileri> sozlesme_array = new ArrayList<KontratBilgileri>();
        sozlesme_array = islemler.kapanan_sozlesme_listesi();
        if (sozlesme_array != null){
            
            for (KontratBilgileri sozlesme : sozlesme_array){
                Object[] eklenenler = { sozlesme.getPlaka(),sozlesme.getMarka(),sozlesme.getTipi(),sozlesme.getVites(),sozlesme.getSon_km(),sozlesme.getDonus_km(),
                    sozlesme.getArac_fiyati(),sozlesme.getKur(),sozlesme.getOdenen_toplam_miktar(),sozlesme.getKdv_bedeli(), sozlesme.getKiralanan_gun_sayisi(),
                    sozlesme.getMusteri_tc(),sozlesme.getMusteri_adi(),sozlesme.getMusteri_soyadi(),sozlesme.getTeslim_eden(),sozlesme.getTel_no(),
                    sozlesme.getBaslangic_tarihi(),sozlesme.getBaslangic_saati(),sozlesme.getBitis_tarihi(),sozlesme.getBitis_saati()};
                
                modelim2.addRow(eklenenler);
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sozlesme_table = new javax.swing.JTable();
        musteriAramaYeri = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        sozlesme_table.setBackground(new java.awt.Color(255, 255, 255));
        sozlesme_table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sozlesme_table.setForeground(new java.awt.Color(0, 0, 204));
        sozlesme_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "PLAKA", "MARKA", "TİPİ", "VİTES", "İLK KM", "SON KM", "GÜNLÜK FİYAT", "KUR", "ODENEN FİYAT", "KDV BEDELİ", "GÜN SAYISI", "MUSTERİ TC", "MUSTERİ AD", "MUSTERİ SOYAD", "TESLİM EDEN", "TEL NO", "BAS. TAR.", "BAS. SAATİ", "BİT. TAR.", "BİT. SAATİ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sozlesme_table.setSelectionBackground(new java.awt.Color(153, 153, 255));
        sozlesme_table.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(sozlesme_table);
        if (sozlesme_table.getColumnModel().getColumnCount() > 0) {
            sozlesme_table.getColumnModel().getColumn(0).setResizable(false);
            sozlesme_table.getColumnModel().getColumn(2).setResizable(false);
        }

        musteriAramaYeri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                musteriAramaYeriKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_search_24px.png"))); // NOI18N
        jLabel1.setText("        ARA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(musteriAramaYeri, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 612, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musteriAramaYeri, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void musteriAramaYeriKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_musteriAramaYeriKeyReleased
        // TODO add your handling code here:

        String ara = musteriAramaYeri.getText();
        dinamikAra(ara);
    }//GEN-LAST:event_musteriAramaYeriKeyReleased

    
     public void dinamikAra(String ara){
        
        TableRowSorter<DefaultTableModel> temp = new TableRowSorter<DefaultTableModel>(modelim2);
        
        sozlesme_table.setRowSorter(temp);
        temp.setRowFilter(RowFilter.regexFilter(ara));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField musteriAramaYeri;
    private javax.swing.JTable sozlesme_table;
    // End of variables declaration//GEN-END:variables
}
