/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import bilgiler.KiralananAracBilgileri;
import db_islemler.ButunDBIslemleri;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author sudeg
 */
public class KiralikAracListeleme extends javax.swing.JPanel {
    
    ButunDBIslemleri islemler = new ButunDBIslemleri();
    DefaultTableModel modelim1 = new DefaultTableModel();
    
    String temp_musteriAd;
    String temp_musteriSoyad;
    String temp_musteriTC;
    String temp_plaka;
    String temp_kur;
    String temp_marka;
    String temp_tip;
    String temp_telno;
    String temp_vites;
    Date temp_bas_tar;
    String temp_bas_sa;
    Date temp_bit_tar;
    String temp_bit_sa;
    int temp_son_km;
    int temp_fiyat;

    /**
     * Creates new form KiralikAracListeleme2
     */
    public KiralikAracListeleme() {
        initComponents();
        
        musteriAramaYeri.setBorder(BorderFactory.createLineBorder(Color.decode("#2C6791")));
        
        kiralik_arac_sayisi.setText("Kiralık Araçların Sayısı: "+islemler.kiralik_arac_sayisi());
        
        modelim1 = (DefaultTableModel) kiralik_arac_table.getModel();
        modelim1.setRowCount(0);
        ArrayList<KiralananAracBilgileri> kiralik_array = new ArrayList<KiralananAracBilgileri>();
        kiralik_array = islemler.kiradaki_arac_listesi();
        if (kiralik_array != null){
            
            for (KiralananAracBilgileri kiralik : kiralik_array){
                Object[] eklenenler = { kiralik.getPlaka(),kiralik.getMarka(),kiralik.getTipi(), kiralik.getArac_fiyati(), kiralik.getKur(), kiralik.getMusteri_tc(),
                    kiralik.getMusteri_adi(),kiralik.getMusteri_soyadi(),kiralik.getTel_no(),kiralik.getBaslangic_tarihi(),kiralik.getBaslangic_saati(),
                    kiralik.getBitis_tarihi(), kiralik.getBitis_saati()};
                
                modelim1.addRow(eklenenler);
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        kiralik_arac_table = new javax.swing.JTable();
        kiralik_arac_sayisi = new javax.swing.JLabel();
        musteriAramaYeri = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        kiralik_arac_table.setBackground(new java.awt.Color(255, 255, 255));
        kiralik_arac_table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kiralik_arac_table.setForeground(new java.awt.Color(0, 0, 204));
        kiralik_arac_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Plaka", "Marka", "Tipi", "Fiyatı", "Kur", "Musteri TC", "Müşteri Adı", "Müsteri Soyadı", "Tel No", "Baş.Tar.", "Baş.Sa.", "Bitiş Tar.", "Bitiş Sa."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        kiralik_arac_table.setSelectionBackground(new java.awt.Color(153, 153, 255));
        kiralik_arac_table.setSelectionForeground(new java.awt.Color(255, 255, 255));
        kiralik_arac_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                kiralik_arac_tableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(kiralik_arac_table);
        kiralik_arac_table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        kiralik_arac_sayisi.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        kiralik_arac_sayisi.setForeground(new java.awt.Color(153, 153, 255));

        musteriAramaYeri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                musteriAramaYeriKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_search_24px.png"))); // NOI18N
        jLabel1.setText("        ARA");

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setText("Plakaya Göre Sırala");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kiralik_arac_sayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33)
                            .addComponent(musteriAramaYeri, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox1)
                .addGap(252, 252, 252))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(kiralik_arac_sayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musteriAramaYeri, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(jCheckBox1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void kiralik_arac_tableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kiralik_arac_tableMouseReleased
        // TODO add your handling code here:
        
            int row = kiralik_arac_table.getSelectedRow();

            if(row>=0){
                String temp_plaka = kiralik_arac_table.getValueAt(row, 0).toString();
                String temp_marka = kiralik_arac_table.getValueAt(row, 1).toString();
                String temp_tip = kiralik_arac_table.getValueAt(row, 2).toString();
                int temp_fiyat = (int)kiralik_arac_table.getValueAt(row, 3);
                String temp_kur = kiralik_arac_table.getValueAt(row, 4).toString();
                String temp_musteriTC = kiralik_arac_table.getValueAt(row, 5).toString();
                String temp_musteriAd = kiralik_arac_table.getValueAt(row, 6).toString();
                String temp_musteriSoyad = kiralik_arac_table.getValueAt(row, 7).toString();
                String temp_telno = kiralik_arac_table.getValueAt(row, 8).toString();
                Date temp_bas_tar = (Date)kiralik_arac_table.getValueAt(row, 9);
                String temp_bas_sa = kiralik_arac_table.getValueAt(row, 10).toString();
                Date temp_bit_tar = (Date)kiralik_arac_table.getValueAt(row, 11);
                String temp_bit_sa = kiralik_arac_table.getValueAt(row, 12).toString();

                this.temp_plaka = temp_plaka  ;
                this.temp_marka = temp_marka  ;
                this.temp_tip = temp_tip ;
                this.temp_fiyat = temp_fiyat;
                this.temp_kur = temp_kur;
                this.temp_musteriTC = temp_musteriTC  ;
                this.temp_musteriAd = temp_musteriAd ;
                this.temp_musteriSoyad = temp_musteriSoyad ;
                this.temp_telno = temp_telno;
                this.temp_bas_tar = temp_bas_tar;
                this.temp_bas_sa = temp_bas_sa;
                this.temp_bit_tar = temp_bit_tar;
                this.temp_bit_sa = temp_bit_sa;
                
        

            
        }

    }//GEN-LAST:event_kiralik_arac_tableMouseReleased
    public void dinamikAra(String ara){
        
        TableRowSorter<DefaultTableModel> temp = new TableRowSorter<DefaultTableModel>(modelim1);
        
        kiralik_arac_table.setRowSorter(temp);
        temp.setRowFilter(RowFilter.regexFilter(ara));
        
    }
    




    private void musteriAramaYeriKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_musteriAramaYeriKeyReleased
        // TODO add your handling code here:

        String ara = musteriAramaYeri.getText();
        dinamikAra(ara);
    }//GEN-LAST:event_musteriAramaYeriKeyReleased

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        
        modelim1.setRowCount(0);
        
        modelim1 = (DefaultTableModel) kiralik_arac_table.getModel();
        modelim1.setRowCount(0);
        ArrayList<KiralananAracBilgileri> kiralik_array = new ArrayList<KiralananAracBilgileri>();
        kiralik_array = islemler.plakaya_gore_kiradaki_arac_listesi();
        if (kiralik_array != null){
            
            for (KiralananAracBilgileri kiralik : kiralik_array){
                Object[] eklenenler = { kiralik.getPlaka(),kiralik.getMarka(),kiralik.getTipi(), kiralik.getArac_fiyati(), kiralik.getKur(), kiralik.getMusteri_tc(),
                    kiralik.getMusteri_adi(),kiralik.getMusteri_soyadi(),kiralik.getTel_no(),kiralik.getBaslangic_tarihi(),kiralik.getBaslangic_saati(),
                    kiralik.getBitis_tarihi(), kiralik.getBitis_saati()};
                
                modelim1.addRow(eklenenler);
                
            }
        }      
        
        
        if(!jCheckBox1.isSelected()){
            
            modelim1.setRowCount(0);
           
            kiralik_array = islemler.kiradaki_arac_listesi();
            if (kiralik_array != null){
            
                for (KiralananAracBilgileri kiralik : kiralik_array){
                    Object[] eklenenler = { kiralik.getPlaka(),kiralik.getMarka(),kiralik.getTipi(), kiralik.getArac_fiyati(), kiralik.getKur(), kiralik.getMusteri_tc(),
                        kiralik.getMusteri_adi(),kiralik.getMusteri_soyadi(),kiralik.getTel_no(),kiralik.getBaslangic_tarihi(),kiralik.getBaslangic_saati(),
                        kiralik.getBitis_tarihi(), kiralik.getBitis_saati()};
                
                    modelim1.addRow(eklenenler);
                
                }
            }
            
        }
        
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kiralik_arac_sayisi;
    private javax.swing.JTable kiralik_arac_table;
    private javax.swing.JTextField musteriAramaYeri;
    // End of variables declaration//GEN-END:variables
}
