/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import bilgiler.MusteriBilgileri;
import db_islemler.ButunDBIslemleri;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author sudeg
 */
public class MusteriListeleme extends javax.swing.JPanel {

   
    ButunDBIslemleri islemler = new ButunDBIslemleri();
    DefaultTableModel modelim2 = new DefaultTableModel();
    
    
    String temp_musteriAd;
    String temp_musteriSoyad;
    String temp_musteriTC;
    String temp_tel_no;
    String temp_adres;
    String temp_sehir;
    int bakiye;



    
    
    /**
     * 
     * Creates new form MusteriListeleme2
     */
    public MusteriListeleme() {
        initComponents();
        
        musteriAramaYeri.setBorder(BorderFactory.createLineBorder(Color.decode("#2C6791")));
        
        modelim2 = (DefaultTableModel) musteri_tablosu.getModel();
        modelim2.setRowCount(0);
        ArrayList<MusteriBilgileri> musteri_array = new ArrayList<MusteriBilgileri>();
        musteri_array = islemler.musteri_listesi();
        if (musteri_array != null){
            
            for (MusteriBilgileri msuteri : musteri_array){
                Object[] eklenenler = { msuteri.getTc(),msuteri.getAd(),msuteri.getSoyad(),msuteri.getTel_no(), msuteri.getAdres(), msuteri.getSehir(),
                    msuteri.getMail(),msuteri.getBakiye()};
                
                modelim2.addRow(eklenenler);
                
            }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        musteri_tablosu = new javax.swing.JTable();
        musteriAramaYeri = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        musteri_tablosu.setBackground(new java.awt.Color(255, 255, 255));
        musteri_tablosu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        musteri_tablosu.setForeground(new java.awt.Color(0, 0, 204));
        musteri_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MUSTERI TC", "AD", "SOYAD", "TEL NO", "ADRES", "SEHİR", "MAIL ADRESİ", "BAKIYE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        musteri_tablosu.setSelectionBackground(new java.awt.Color(153, 153, 255));
        musteri_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                musteri_tablosuMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(musteri_tablosu);
        if (musteri_tablosu.getColumnModel().getColumnCount() > 0) {
            musteri_tablosu.getColumnModel().getColumn(0).setPreferredWidth(30);
            musteri_tablosu.getColumnModel().getColumn(1).setPreferredWidth(30);
            musteri_tablosu.getColumnModel().getColumn(2).setPreferredWidth(30);
            musteri_tablosu.getColumnModel().getColumn(3).setPreferredWidth(30);
            musteri_tablosu.getColumnModel().getColumn(6).setPreferredWidth(30);
            musteri_tablosu.getColumnModel().getColumn(7).setPreferredWidth(30);
        }

        musteriAramaYeri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                musteriAramaYeriKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_search_24px.png"))); // NOI18N
        jLabel1.setText("        ARA");

        jCheckBox1.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setText("TC'ye Göre Sırala");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox2.setText("AD'a Göre Sırala");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(musteriAramaYeri, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(629, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox1)
                .addGap(33, 33, 33)
                .addComponent(jCheckBox2)
                .addGap(109, 109, 109))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(musteriAramaYeri, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void musteri_tablosuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musteri_tablosuMouseReleased
        // TODO add your handling code here:
        

            int row = musteri_tablosu.getSelectedRow();

            if(row>=0){
                String tc = musteri_tablosu.getValueAt(row, 0).toString();
                String ad = musteri_tablosu.getValueAt(row, 1).toString();
                String soyad = musteri_tablosu.getValueAt(row, 2).toString();
                String tel_no = musteri_tablosu.getValueAt(row, 3).toString();
                String adres = musteri_tablosu.getValueAt(row, 4).toString();
                String sehir = musteri_tablosu.getValueAt(row, 5).toString();
                int bakiye = (int) musteri_tablosu.getValueAt(row, 7);

                this.temp_musteriAd = ad ;
                this.temp_musteriSoyad = soyad;
                this.temp_musteriTC = tc;
                this.temp_tel_no = tel_no;
                this.temp_adres = adres;
                this.temp_sehir = sehir;
                this.bakiye = bakiye;

                

            
        }

    }//GEN-LAST:event_musteri_tablosuMouseReleased

     public void dinamikAra(String ara){
        
        TableRowSorter<DefaultTableModel> temp = new TableRowSorter<DefaultTableModel>(modelim2);
        
        musteri_tablosu.setRowSorter(temp);
        temp.setRowFilter(RowFilter.regexFilter(ara));
        
    }
    
    
    
    private void musteriAramaYeriKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_musteriAramaYeriKeyReleased
        // TODO add your handling code here:

        String ara = musteriAramaYeri.getText();
        dinamikAra(ara);

    }//GEN-LAST:event_musteriAramaYeriKeyReleased

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        
        modelim2.setRowCount(0);
        jCheckBox2.setSelected(false);
        
        modelim2 = (DefaultTableModel) musteri_tablosu.getModel();
        modelim2.setRowCount(0);
        ArrayList<MusteriBilgileri> musteri_array = new ArrayList<MusteriBilgileri>();
        musteri_array = islemler.tc_gore_sirali_musteri_listesi();
        if (musteri_array != null){
            
            for (MusteriBilgileri msuteri : musteri_array){
                Object[] eklenenler = { msuteri.getTc(),msuteri.getAd(),msuteri.getSoyad(),msuteri.getTel_no(), msuteri.getAdres(), msuteri.getSehir(),
                    msuteri.getMail(), msuteri.getBakiye()};
                
                modelim2.addRow(eklenenler);
                
            }
        }
        
        if(!jCheckBox1.isSelected()){
            if(!jCheckBox2.isSelected()){
                modelim2.setRowCount(0);
                musteri_array = islemler.musteri_listesi();
                if (musteri_array != null){
            
                    for (MusteriBilgileri msuteri : musteri_array){
                        Object[] eklenenler = { msuteri.getTc(),msuteri.getAd(),msuteri.getSoyad(),msuteri.getTel_no(), msuteri.getAdres(), msuteri.getSehir(),
                        msuteri.getMail(),msuteri.getBakiye()};
                
                    modelim2.addRow(eklenenler);
                
                    }
                }
                
            }
            
        }
        
        
        
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        modelim2.setRowCount(0);
        jCheckBox1.setSelected(false);
        modelim2 = (DefaultTableModel) musteri_tablosu.getModel();
        modelim2.setRowCount(0);
        ArrayList<MusteriBilgileri> musteri_array = new ArrayList<MusteriBilgileri>();
        musteri_array = islemler.ada_gore_sirali_musteri_listesi();
        if (musteri_array != null){
            
            for (MusteriBilgileri msuteri : musteri_array){
                Object[] eklenenler = { msuteri.getTc(),msuteri.getAd(),msuteri.getSoyad(),msuteri.getTel_no(), msuteri.getAdres(), msuteri.getSehir(),
                    msuteri.getMail(),msuteri.getBakiye()};
                
                modelim2.addRow(eklenenler);
                
            }
        }
        
        if(!jCheckBox1.isSelected()){
            if(!jCheckBox2.isSelected()){
                modelim2.setRowCount(0);
                musteri_array = islemler.musteri_listesi();
                if (musteri_array != null){
            
                    for (MusteriBilgileri msuteri : musteri_array){
                        Object[] eklenenler = { msuteri.getTc(),msuteri.getAd(),msuteri.getSoyad(),msuteri.getTel_no(), msuteri.getAdres(), msuteri.getSehir(),
                        msuteri.getMail(),msuteri.getBakiye()};
                
                    modelim2.addRow(eklenenler);
                
                    }
                }
                
            }
            
        }
        
        
    }//GEN-LAST:event_jCheckBox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField musteriAramaYeri;
    public javax.swing.JTable musteri_tablosu;
    // End of variables declaration//GEN-END:variables
}
