/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import bilgiler.PersonelBilgileri;
import db_islemler.ButunDBIslemleri;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author sudeg
 */
public class Personel_islemleri extends javax.swing.JPanel {
    
    ButunDBIslemleri islemler = new ButunDBIslemleri();
    DefaultTableModel modelim3 = new DefaultTableModel();

    /**
     * Creates new form PersonelListele
     */
    public Personel_islemleri() {
        initComponents();
        
        ad_text.setBorder(BorderFactory.createLineBorder(Color.decode("#2C6791")));
        soyad_text.setBorder(BorderFactory.createLineBorder(Color.decode("#2C6791")));
        nick_text.setBorder(BorderFactory.createLineBorder(Color.decode("#2C6791")));
        sifre_txt.setBorder(BorderFactory.createLineBorder(Color.decode("#2C6791")));
        jPanel2.setBorder(BorderFactory.createLineBorder(Color.decode("#2C6791")));
        
        personelAramaYeri.setBorder(BorderFactory.createLineBorder(Color.decode("#2C6791")));
        
        
        modelim3 = (DefaultTableModel) personelTablo.getModel();
        modelim3.setRowCount(0);
        ArrayList<PersonelBilgileri> personel_array = new ArrayList<PersonelBilgileri>();
        personel_array = islemler.kul_listele();
        if (personel_array != null){
            
            for (PersonelBilgileri personel : personel_array){
                Object[] eklenenler = { personel.getId(),personel.getAd(),personel.getSoyad(),personel.getNick(),personel.getSifre(),personel.getYetki() };
                
                modelim3.addRow(eklenenler);
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deneme = new javax.swing.JPanel();
        personelAramaYeri = new javax.swing.JTextField();
        bos_arac_sayisi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        personelTablo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ad_text = new javax.swing.JTextField();
        soyad_text = new javax.swing.JTextField();
        nick_text = new javax.swing.JTextField();
        sifre_txt = new javax.swing.JTextField();
        yetki_combox = new javax.swing.JComboBox<>();
        kaydet_butonu2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        deneme.setBackground(new java.awt.Color(255, 255, 255));
        deneme.setPreferredSize(new java.awt.Dimension(1282, 883));

        personelAramaYeri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                personelAramaYeriKeyReleased(evt);
            }
        });

        bos_arac_sayisi.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bos_arac_sayisi.setForeground(new java.awt.Color(153, 153, 255));

        personelTablo.setBackground(new java.awt.Color(255, 255, 255));
        personelTablo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        personelTablo.setForeground(new java.awt.Color(0, 0, 204));
        personelTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "ADI", "SOYADI", "KULLANICI ADI", "ŞİFRE", "YETKİ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        personelTablo.setGridColor(new java.awt.Color(0, 0, 0));
        personelTablo.setSelectionBackground(new java.awt.Color(153, 153, 255));
        personelTablo.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(personelTablo);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_search_24px.png"))); // NOI18N
        jLabel1.setText("        ARA");

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("PERSONEL SİL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("PERSONEL DEĞİŞTİR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_refresh_24px.png"))); // NOI18N
        jButton3.setText("  ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("PERSONELİN ADI");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("PERSONELİN SOYADI");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("KULLANICI ADI");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("ŞİFRESİ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("YETKİ");

        yetki_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "SUPERVISOR", "MUHASEBE", "SATIŞ" }));

        kaydet_butonu2.setBackground(new java.awt.Color(0, 0, 153));
        kaydet_butonu2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        kaydet_butonu2.setForeground(new java.awt.Color(255, 255, 255));
        kaydet_butonu2.setText("KAYDET");
        kaydet_butonu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydet_butonu2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(175, 175, 175)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sifre_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soyad_text, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yetki_combox, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ad_text, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nick_text, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 362, Short.MAX_VALUE)
                        .addComponent(kaydet_butonu2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ad_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soyad_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nick_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(kaydet_butonu2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sifre_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(yetki_combox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout denemeLayout = new javax.swing.GroupLayout(deneme);
        deneme.setLayout(denemeLayout);
        denemeLayout.setHorizontalGroup(
            denemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(denemeLayout.createSequentialGroup()
                .addGroup(denemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(denemeLayout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jButton1)
                        .addGap(393, 393, 393)
                        .addComponent(jButton2))
                    .addGroup(denemeLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addGroup(denemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(denemeLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(personelAramaYeri, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(denemeLayout.createSequentialGroup()
                .addGroup(denemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bos_arac_sayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        denemeLayout.setVerticalGroup(
            denemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(denemeLayout.createSequentialGroup()
                .addGroup(denemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(denemeLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(bos_arac_sayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(denemeLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(denemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personelAramaYeri, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(denemeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(deneme, javax.swing.GroupLayout.PREFERRED_SIZE, 1435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deneme, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void personelAramaYeriKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_personelAramaYeriKeyReleased
        // TODO add your handling code here:

        String ara = personelAramaYeri.getText();
        dinamikAra(ara);
    }//GEN-LAST:event_personelAramaYeriKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        int row = personelTablo.getSelectedRow();
        if(row>=0){
            
            int id = (int) personelTablo.getValueAt(row, 0);
            String ad = personelTablo.getValueAt(row, 1).toString();
            String soyad = personelTablo.getValueAt(row, 2).toString();
            String kul_adi = personelTablo.getValueAt(row, 3).toString();
            String sifre = personelTablo.getValueAt(row, 4).toString();
            String yetki = personelTablo.getValueAt(row, 5).toString();
            
            new PerGunEkrani(id,ad,soyad,kul_adi,sifre,yetki).setVisible(true);
            
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int row = personelTablo.getSelectedRow();
        if(row>=0){
            
            int id = (int) personelTablo.getValueAt(row, 0);
            islemler.personel_sil(id);
            
            
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void kaydet_butonu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydet_butonu2ActionPerformed
        // TODO add your handling code here:

        String ad = ad_text.getText();
        String soyad = soyad_text.getText();
        String nick = nick_text.getText();
        String sifre = sifre_txt.getText();
        String yetki = yetki_combox.getSelectedItem().toString();

        ad_text.setText("");
        soyad_text.setText("");
        nick_text.setText("");
        sifre_txt.setText("");

        islemler.personel_ekle(ad,soyad,nick,sifre,yetki);

    }//GEN-LAST:event_kaydet_butonu2ActionPerformed

    public void refreshTable(){
        
        modelim3 = (DefaultTableModel) personelTablo.getModel();
        modelim3.setRowCount(0);
        ArrayList<PersonelBilgileri> personel_array = new ArrayList<PersonelBilgileri>();
        personel_array = islemler.kul_listele();
        if (personel_array != null){
            
            for (PersonelBilgileri personel : personel_array){
                Object[] eklenenler = { personel.getId(),personel.getAd(),personel.getSoyad(),personel.getNick(),personel.getSifre(),personel.getYetki() };
                
                modelim3.addRow(eklenenler);
                
            }
        }
        
    }
    
    
    
    
    public void dinamikAra(String ara){
        
        TableRowSorter<DefaultTableModel> temp2 = new TableRowSorter<DefaultTableModel>(modelim3);
        
        personelTablo.setRowSorter(temp2);
        temp2.setRowFilter(RowFilter.regexFilter(ara));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_text;
    private javax.swing.JLabel bos_arac_sayisi;
    private javax.swing.JPanel deneme;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton kaydet_butonu2;
    private javax.swing.JTextField nick_text;
    private javax.swing.JTextField personelAramaYeri;
    private javax.swing.JTable personelTablo;
    private javax.swing.JTextField sifre_txt;
    private javax.swing.JTextField soyad_text;
    private javax.swing.JComboBox<String> yetki_combox;
    // End of variables declaration//GEN-END:variables
}
